<?php
    $title = "Aula 04 de PHP";
    $desenvolvedor = "Rafael Alves Florindo";

    $tutoriais = array(
        0 => array('id'=>'1', 
            'titulo'=>'Introdução a Linguagem PHP', 
            'autor'=>'Rafael A. Florindo', 
            'data'=>'2022-05-12', 
            'descricao'=>'A popular general-purpose scripting language that is especially suited to web development.
        Fast, flexible and pragmatic, PHP powers everything from your blog to the most popular websites in the world.',
            'imagem'=>'img/php1.jpeg', 
            'title_img'=>'Introdução a Linguagem PHP'),
        1 => array('id'=>'2', 
            'titulo'=>'Integrando o PHP em arquivos HTML', 
            'autor'=>'Ricardo A. Florindo', 
            'data'=>'2022-05-12', 
            'descricao'=>'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
            'imagem'=>'img/php2.jpg', 
            'title_img'=>'Integrando o PHP em arquivos HTML'),
        2 => array('id'=>'3', 
            'titulo'=>'Aplicando estilos em páginas WEB', 
            'autor'=>'Arthur Florindo', 
            'data'=>'2022-05-12', 
            'descricao'=>'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
            'imagem'=>'img/css.jpeg', 
            'title_img'=>'Aplicando estilos em páginas WEB'),
        3 => array('id'=>'4', 
            'titulo'=>'Aplicando recursos assincronos com JS e PHP', 
            'autor'=>'Murilo Florindo', 
            'data'=>'2022-05-12', 
            'descricao'=>'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
            'imagem'=>'img/js.jpg', 
            'title_img'=>'Aplicando recursos assincronos com JS e PHP'),
        4 => array('id'=>'5', 
            'titulo'=>'Integrando um API entre Java e PHP', 
            'autor'=>'Davi Florindo', 
            'data'=>'2022-05-12', 
            'descricao'=>'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.',
            'imagem'=>'img/node.jpg', 
            'title_img'=>'Integrando um API entre Java e PHP'),
    );